# frozen_string_literal: true

require_relative "sunbird/version"
require_relative "sunbird/content/ruby_source"
require_relative "sunbird/dialogue/catalog"
require_relative "sunbird/dialogue/loader"

require_relative "sunbird/component"
require_relative "sunbird/prototype"
require_relative "sunbird/prototype/catalog"
require_relative "sunbird/prototype/loader"
require_relative "sunbird/character"
require_relative "sunbird/effect"
require_relative "sunbird/direction"

require_relative "sunbird/world/component_table"
require_relative "sunbird/world/relations"
require_relative "sunbird/world/view"
require_relative "sunbird/world"

require_relative "sunbird/level"
require_relative "sunbird/level/terrain"
require_relative "sunbird/level/loader"
require_relative "sunbird/session"

require_relative "sunbird/input/action"
require_relative "sunbird/input/mapper"
require_relative "sunbird/input/handoff"
require_relative "sunbird/input/snapshot"

require_relative "sunbird/simulation/commands"
require_relative "sunbird/simulation/movement"
require_relative "sunbird/simulation/pathfinder"
require_relative "sunbird/simulation/bindings"
require_relative "sunbird/simulation/executor"
require_relative "sunbird/simulation"
require_relative "sunbird/turn_planner"

require_relative "sunbird/mode_stack"
require_relative "sunbird/mode/transitions"
require_relative "sunbird/mode/dialogue"
require_relative "sunbird/mode/play"

require_relative "sunbird/render/scene"
require_relative "sunbird/render/projector"
require_relative "sunbird/render/ascii"
require_relative "sunbird/render/asset_catalog"
require_relative "sunbird/render/kitty"
require_relative "sunbird/render/selector"

require_relative "sunbird/host"
require_relative "sunbird/host/terminal_capabilities"
require_relative "sunbird/host/terminal_input"
require_relative "sunbird/host/terminal"
require_relative "sunbird/app"
